M48
; DRILL file {KiCad 7.0.7} date Tue Aug 29 08:21:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-29T08:21:59+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X5.5906Y-4.4016
T2
X5.7633Y-4.0551
X5.7633Y-4.1551
T0
M30
